services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-scheduling-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      LOG_CHANNEL: stack
    depends_on:
      - db
    networks:
      - medical-scheduling-network

  db:
    image: mysql:8.0
    container_name: medical-scheduling-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: medical_scheduling
      MYSQL_USER: user
      MYSQL_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - medical-scheduling-network

  mockapi:
    image: node:18-alpine
    container_name: medical-scheduling-mockapi
    working_dir: /app
    volumes:
      - ./resources/mocks:/app/mocks
    command: sh -c "npm install -g json-server && json-server --watch /app/mocks/doctors.json --port 3000"
    ports:
      - "3000:3000"
    networks:
      - medical-scheduling-network

volumes:
  db_data:
networks:
  medical-scheduling-network:
    driver: bridge