services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-scheduling-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      LOG_CHANNEL: stack
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: medical-scheduling-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: medical_scheduling
      MYSQL_USER: user
      MYSQL_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3310:3306"

volumes:
  db_data: